---
# vagrant.yml
- name: Shankel Stack
  hosts: all
  user: vagrant
  sudo: True

  vars:
    hostname: sandbox.shankel.com
    username: vagrant

  tasks:
  - name: Update APT package cache
    apt: update_cache=yes

  - name: Install packages
    apt: pkg={{ item }} state=installed
    with_items:
      - bash-completion
      - curl
      - dnsutils
      - fail2ban
      - htop
      - imagemagick
      - iotop
      - liblzma-dev
      - libpcre3-dev
      - mosh
      - openssl
      - pkg-config
      - realpath
      - vim
      - zlib1g-dev
      - python-setuptools
      - mono-complete
  #    - paramiko


  - name: add 'chris-lea' PPA for node.js
    apt_repository: repo=ppa:chris-lea/node.js

  - name: Install nodeJS
    apt: pkg=nodejs update_cache=yes state=latest

  - name: Install Pip
    easy_install: name=pip

  - include: ag.yml

  - name: install supervisor
    apt: pkg=supervisor

  - name: prepare /etc/supervisor directory
    file: path=/etc/supervisor state=directory owner=root group=root mode=0755

  - name: copy supervisord.conf
    copy: src=./supervisord_etc.conf dest=/etc/supervisord.conf owner=root group=root mode=0755

  - name: copy supervisord init script
    copy: src=./supervisord_init.conf dest=/etc/init/supervisord.conf owner=root group=root mode=0755

  - name: install node_server
    copy: src=./node_server_supervisor.conf dest=/etc/supervisor/conf.d/node_server_supervisor.conf owner=root group=root mode=0644

  - name: copy node_server supervisord config
    template: src=node_server_init.j2 dest=/etc/supervisor/node_server.conf owner=root group=root mode=0644

  - name: intall winston
    npm: name=winston path=/usr/js_webgames/nodejs

  - name: install express
    npm: name=express path=/usr/js_webgames/nodejs

  - name: start supervisord
    service: name=supervisord enabled=yes state=started

  - name: reload supervisor
    sudo: yes
    shell: supervisorctl reload
